// ─── Chinese Astrology — Bazi (Four Pillars of Destiny) calculator ──────────
// Wraps lunar-javascript for accurate Chinese lunisolar calendar + solar terms,
// then exposes a clean typed result for the UI layer.

import { Solar } from 'lunar-javascript'
import {
  STEMS, BRANCHES,
  NOBLEMAN_BY_DAY_MASTER, getTrioStars,
  ACADEMIC_BY_DAY_MASTER, GOAT_BLADE_BY_DAY_MASTER, SKY_HORSE_BY_MONTH,
  SIX_HARMONIES, THREE_HARMONIES, SIX_CLASHES, PUNISHMENTS,
  type Element,
} from './chinese-data'

export interface Pillar {
  label:    'Year' | 'Month' | 'Day' | 'Hour'
  stemChar: string         // 甲, 乙, ...
  branchChar: string       // 子, 丑, ...
  ganZhi:   string         // 甲子
  stemElement:   Element
  branchElement: Element
  hiddenStems:   string[]  // hidden stem chars in branch
  god:      string         // 10 Gods name (Chinese, mapped via TEN_GODS)
  nayin:    string         // sound of earth
}

export interface LuckPillar {
  startYear: number
  endYear:   number
  age:       number        // age at start
  stemChar:  string
  branchChar: string
  ganZhi:    string
}

export interface SpecialStarHit {
  starKey:  string  // key into SPECIAL_STARS
  pillar:   'Year' | 'Month' | 'Day' | 'Hour'
  branch:   string
}

export interface BranchInteraction {
  type:     'harmony6' | 'harmony3' | 'clash' | 'punishment'
  branches: string[]
  pillars:  string[]   // pillar labels involved
  element?: Element    // for harmonies
  label:    string     // human-readable
}

export interface BaziResult {
  pillars: {
    year:  Pillar
    month: Pillar
    day:   Pillar
    hour:  Pillar
  }
  dayMaster: string             // stem char of Day pillar
  dayMasterElement: Element
  elementCounts: Record<Element, number>     // weighted balance
  elementPercent: Record<Element, number>    // 0-100
  dominantElement: Element
  weakestElement:  Element
  favorableElements: Element[]   // simple heuristic
  luckPillars: LuckPillar[]
  yearAnimal:  string
  monthAnimal: string
  dayAnimal:   string
  hourAnimal:  string
  solarTerm:   string
  lunarDate:   string
  specialStars: SpecialStarHit[]
  interactions: BranchInteraction[]
}

export interface AnnualTransit {
  year:        number
  ganZhi:      string
  stemChar:    string
  branchChar:  string
  stemElement: Element
  branchElement: Element
  god:         string             // 10 Gods name (Chinese key)
  interactions: BranchInteraction[]
  newSpecialStars: SpecialStarHit[]  // stars activated by transit branch hitting natal
}

export interface CompatibilityResult {
  dayMasterRelation: string  // "Same Friend", "Generates", "Generated by", "Controls", "Controlled by"
  dmScore:           number  // 0-100
  branchScore:       number  // 0-100
  elementScore:      number  // 0-100 (complementarity of element profiles)
  overallScore:      number  // 0-100
  notes:             string[]
  interactions:      BranchInteraction[]   // between the two charts
}

// Map Chinese stem element char to English
const ELEMENT_MAP: Record<string, Element> = {
  '木': 'Wood', '火': 'Fire', '土': 'Earth', '金': 'Metal', '水': 'Water',
}

function stemElement(char: string): Element {
  return STEMS[char]?.element ?? 'Earth'
}

function branchElement(char: string): Element {
  return BRANCHES[char]?.element ?? 'Earth'
}

/**
 * Compute the weighted element balance from the 4 pillars.
 * - Stem element: weight 1
 * - Branch main element: weight 1
 * - Hidden stem elements: weight 0.3 each
 */
function computeElementBalance(stems: string[], branches: string[]): Record<Element, number> {
  const counts: Record<Element, number> = { Wood: 0, Fire: 0, Earth: 0, Metal: 0, Water: 0 }

  for (const s of stems) {
    counts[stemElement(s)] += 1
  }
  for (const b of branches) {
    counts[branchElement(b)] += 1
    const hidden = BRANCHES[b]?.hiddenStems ?? []
    for (const h of hidden) {
      counts[stemElement(h)] += 0.3
    }
  }
  return counts
}

/**
 * Determine favorable elements via a simple heuristic:
 * - If Day Master is strong (count >= avg), favor elements that drain/control it
 * - If weak, favor elements that produce/support it
 * This is a simplification of classical yong shen analysis.
 */
function determineFavorable(dmElement: Element, counts: Record<Element, number>): Element[] {
  const total = Object.values(counts).reduce((a, b) => a + b, 0)
  const avg = total / 5
  const dmStrength = counts[dmElement]

  // Generation cycle: Wood→Fire→Earth→Metal→Water→Wood
  const GENERATES: Record<Element, Element> = { Wood: 'Fire', Fire: 'Earth', Earth: 'Metal', Metal: 'Water', Water: 'Wood' }
  const GENERATED_BY: Record<Element, Element> = { Wood: 'Water', Fire: 'Wood', Earth: 'Fire', Metal: 'Earth', Water: 'Metal' }
  const CONTROLS: Record<Element, Element> = { Wood: 'Earth', Earth: 'Water', Water: 'Fire', Fire: 'Metal', Metal: 'Wood' }
  const CONTROLLED_BY: Record<Element, Element> = { Wood: 'Metal', Metal: 'Fire', Fire: 'Water', Water: 'Earth', Earth: 'Wood' }

  if (dmStrength >= avg * 1.1) {
    // Strong Day Master → drain (output) or control
    return [GENERATES[dmElement], CONTROLLED_BY[dmElement], CONTROLS[dmElement]]
  } else {
    // Weak Day Master → produce (resource) or same element (peer)
    return [GENERATED_BY[dmElement], dmElement]
  }
}

/**
 * Calculate Bazi from solar (Gregorian) date and time.
 * @param year   Gregorian year
 * @param month  1-12
 * @param day    1-31
 * @param hour   0-23 (local solar time)
 * @param minute 0-59
 * @param gender 'male' | 'female' (affects luck pillar direction)
 */
export function calcBazi(
  year: number,
  month: number,
  day: number,
  hour: number,
  minute: number,
  gender: 'male' | 'female' = 'male'
): BaziResult {
  const solar = Solar.fromYmdHms(year, month, day, hour, minute, 0)
  const lunar = solar.getLunar()
  const ec = lunar.getEightChar()

  const yearStem = ec.getYearGan()
  const yearBranch = ec.getYearZhi()
  const monthStem = ec.getMonthGan()
  const monthBranch = ec.getMonthZhi()
  const dayStem = ec.getDayGan()
  const dayBranch = ec.getDayZhi()
  const hourStem = ec.getTimeGan()
  const hourBranch = ec.getTimeZhi()

  const stems = [yearStem, monthStem, dayStem, hourStem]
  const branches = [yearBranch, monthBranch, dayBranch, hourBranch]

  // 10 Gods relative to Day Master (Day Master itself = 比肩 Friend)
  const yearGod  = ec.getYearShiShenGan()
  const monthGod = ec.getMonthShiShenGan()
  const hourGod  = ec.getTimeShiShenGan()

  const buildPillar = (
    label: Pillar['label'],
    stem: string,
    branch: string,
    god: string,
    nayin: string
  ): Pillar => ({
    label,
    stemChar: stem,
    branchChar: branch,
    ganZhi: stem + branch,
    stemElement: stemElement(stem),
    branchElement: branchElement(branch),
    hiddenStems: BRANCHES[branch]?.hiddenStems ?? [],
    god,
    nayin,
  })

  const pillars = {
    year:  buildPillar('Year',  yearStem,  yearBranch,  yearGod,  ec.getYearNaYin()),
    month: buildPillar('Month', monthStem, monthBranch, monthGod, ec.getMonthNaYin()),
    day:   buildPillar('Day',   dayStem,   dayBranch,   '比肩',   ec.getDayNaYin()),
    hour:  buildPillar('Hour',  hourStem,  hourBranch,  hourGod,  ec.getTimeNaYin()),
  }

  const counts = computeElementBalance(stems, branches)
  const total = Object.values(counts).reduce((a, b) => a + b, 0)
  const percents: Record<Element, number> = {
    Wood:  Math.round((counts.Wood  / total) * 100),
    Fire:  Math.round((counts.Fire  / total) * 100),
    Earth: Math.round((counts.Earth / total) * 100),
    Metal: Math.round((counts.Metal / total) * 100),
    Water: Math.round((counts.Water / total) * 100),
  }

  const dmElement = stemElement(dayStem)

  // Find dominant & weakest
  const sorted = (Object.keys(counts) as Element[]).sort((a, b) => counts[b] - counts[a])
  const dominant = sorted[0]
  const weakest = sorted[sorted.length - 1]

  const favorable = determineFavorable(dmElement, counts)

  // Luck pillars (Da Yun) — 8 pillars of 10 years each
  const yunGenderCode = gender === 'male' ? 1 : 0
  const yun = ec.getYun(yunGenderCode)
  const daYunList = yun.getDaYun()
  const luckPillars: LuckPillar[] = []
  // First entry is the "small luck" before the first proper Da Yun, skip it.
  for (let i = 1; i < Math.min(daYunList.length, 9); i++) {
    const dy = daYunList[i]
    const gz = dy.getGanZhi()
    if (!gz || gz.length < 2) continue
    luckPillars.push({
      startYear: dy.getStartYear(),
      endYear:   dy.getEndYear(),
      age:       dy.getStartAge(),
      stemChar:  gz[0],
      branchChar: gz[1],
      ganZhi:    gz,
    })
  }

  // ── Special Stars (Shen Sha) ──
  const pillarLabels: Pillar['label'][] = ['Year', 'Month', 'Day', 'Hour']
  const specialStars = computeSpecialStars(dayStem, yearBranch, dayBranch, monthBranch, branches, pillarLabels)

  // ── Branch Interactions (within natal chart) ──
  const interactions = computeBranchInteractions(branches, pillarLabels)

  return {
    pillars,
    dayMaster: dayStem,
    dayMasterElement: dmElement,
    elementCounts: counts,
    elementPercent: percents,
    dominantElement: dominant,
    weakestElement:  weakest,
    favorableElements: favorable,
    luckPillars,
    yearAnimal:  BRANCHES[yearBranch]?.animal  ?? '',
    monthAnimal: BRANCHES[monthBranch]?.animal ?? '',
    dayAnimal:   BRANCHES[dayBranch]?.animal   ?? '',
    hourAnimal:  BRANCHES[hourBranch]?.animal  ?? '',
    solarTerm:   lunar.getJieQi() || lunar.getPrevJieQi().getName(),
    lunarDate:   `${lunar.getYearInChinese()}年${lunar.getMonthInChinese()}月${lunar.getDayInChinese()}`,
    specialStars,
    interactions,
  }
}

// ─── Special Stars Analysis ──────────────────────────────────────────────────

function computeSpecialStars(
  dayStem: string,
  yearBranch: string,
  dayBranch: string,
  monthBranch: string,
  allBranches: string[],
  pillarLabels: Pillar['label'][]
): SpecialStarHit[] {
  const hits: SpecialStarHit[] = []

  const addHit = (key: string, branch: string) => {
    const idx = allBranches.indexOf(branch)
    if (idx >= 0) {
      hits.push({ starKey: key, pillar: pillarLabels[idx], branch })
    }
  }

  // Heavenly Nobleman (天乙贵人) — by Day Master
  const noblemanBranches = NOBLEMAN_BY_DAY_MASTER[dayStem] ?? []
  for (const nb of noblemanBranches) addHit('nobleman', nb)

  // Trio-based stars (Peach Blossom, Travel Horse, General, Solitary) — anchored on Day Branch
  // Tradition uses Day Branch as primary; Year Branch secondary.
  const trio = getTrioStars(dayBranch) || getTrioStars(yearBranch)
  if (trio) {
    addHit('peachBlossom', trio.peachBlossom)
    addHit('travelHorse',  trio.travelHorse)
    addHit('general',      trio.general)
    addHit('solitary',     trio.solitary)
  }

  // Academic Star (文昌) — by Day Master
  const academic = ACADEMIC_BY_DAY_MASTER[dayStem]
  if (academic) addHit('academic', academic)

  // Goat Blade (羊刃) — by Day Master (Yang stems only)
  const goat = GOAT_BLADE_BY_DAY_MASTER[dayStem]
  if (goat) addHit('goatBlade', goat)

  // Sky Horse (天马) — by Month Branch
  const skyHorse = SKY_HORSE_BY_MONTH[monthBranch]
  if (skyHorse) addHit('skyHorse', skyHorse)

  // Deduplicate (same star + same pillar)
  const seen = new Set<string>()
  return hits.filter(h => {
    const key = `${h.starKey}-${h.pillar}-${h.branch}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
}

// ─── Branch Interactions ─────────────────────────────────────────────────────

function computeBranchInteractions(
  branches: string[],
  pillarLabels: Pillar['label'][]
): BranchInteraction[] {
  const interactions: BranchInteraction[] = []
  const present = new Set(branches)

  const labelOf = (b: string): string[] => {
    const labels: string[] = []
    branches.forEach((br, i) => { if (br === b) labels.push(pillarLabels[i]) })
    return labels
  }

  // Six Harmonies
  for (const [a, b, el] of SIX_HARMONIES) {
    if (present.has(a) && present.has(b)) {
      interactions.push({
        type: 'harmony6',
        branches: [a, b],
        pillars: Array.from(new Set(labelOf(a).concat(labelOf(b)))),
        element: el,
        label: `${a}+${b} Six Harmony → ${el}`,
      })
    }
  }

  // Three Harmonies (full or half)
  for (const trio of THREE_HARMONIES) {
    const found = trio.branches.filter(b => present.has(b))
    if (found.length >= 2) {
      interactions.push({
        type: 'harmony3',
        branches: found,
        pillars: Array.from(new Set(found.flatMap(labelOf))),
        element: trio.element,
        label: found.length === 3
          ? `${trio.branches.join('+')} Full Three Harmony → ${trio.element}`
          : `${found.join('+')} Half Three Harmony → ${trio.element}`,
      })
    }
  }

  // Six Clashes
  for (const [a, b] of SIX_CLASHES) {
    if (present.has(a) && present.has(b)) {
      interactions.push({
        type: 'clash',
        branches: [a, b],
        pillars: Array.from(new Set(labelOf(a).concat(labelOf(b)))),
        label: `${a}↔${b} Six Clash`,
      })
    }
  }

  // Punishments
  for (const pun of PUNISHMENTS) {
    if (pun.branches.length === 3) {
      // All three required
      if (pun.branches.every(b => present.has(b))) {
        interactions.push({
          type: 'punishment',
          branches: pun.branches,
          pillars: Array.from(new Set(pun.branches.flatMap(labelOf))),
          label: `${pun.branches.join('+')} ${pun.type}`,
        })
      }
    } else if (pun.branches.length === 2) {
      const [a, b] = pun.branches
      if (a === b) {
        // Self-punishment: needs branch to appear twice
        if (branches.filter(x => x === a).length >= 2) {
          interactions.push({
            type: 'punishment',
            branches: [a, a],
            pillars: labelOf(a),
            label: `${a}+${a} ${pun.type}`,
          })
        }
      } else if (present.has(a) && present.has(b)) {
        interactions.push({
          type: 'punishment',
          branches: [a, b],
          pillars: Array.from(new Set(labelOf(a).concat(labelOf(b)))),
          label: `${a}+${b} ${pun.type}`,
        })
      }
    }
  }

  return interactions
}

// ─── Annual Transit ──────────────────────────────────────────────────────────

const TEN_GODS_TABLE: Record<string, Record<string, string>> = (() => {
  // Build a [DayMaster][OtherStem] → 10 Gods name table
  // Using stem element + polarity to derive the relationship
  const ELEMENT_OF: Record<string, Element> = {}
  const POLARITY_OF: Record<string, Polarity> = {} as Record<string, Polarity>
  for (const [c, s] of Object.entries(STEMS)) {
    ELEMENT_OF[c] = s.element
    POLARITY_OF[c] = s.polarity
  }

  const GENERATES: Record<Element, Element> = { Wood: 'Fire', Fire: 'Earth', Earth: 'Metal', Metal: 'Water', Water: 'Wood' }
  const CONTROLS: Record<Element, Element>  = { Wood: 'Earth', Earth: 'Water', Water: 'Fire', Fire: 'Metal', Metal: 'Wood' }

  const table: Record<string, Record<string, string>> = {}
  for (const dm of Object.keys(STEMS)) {
    table[dm] = {}
    for (const other of Object.keys(STEMS)) {
      const dmEl = ELEMENT_OF[dm]
      const otEl = ELEMENT_OF[other]
      const sameP = POLARITY_OF[dm] === POLARITY_OF[other]

      let god = ''
      if (otEl === dmEl) {
        god = sameP ? '比肩' : '劫财'
      } else if (GENERATES[dmEl] === otEl) {
        // DM generates other = output
        god = sameP ? '食神' : '伤官'
      } else if (CONTROLS[dmEl] === otEl) {
        // DM controls other = wealth
        god = sameP ? '偏财' : '正财'
      } else if (CONTROLS[otEl] === dmEl) {
        // Other controls DM = officer
        god = sameP ? '七杀' : '正官'
      } else if (GENERATES[otEl] === dmEl) {
        // Other generates DM = resource
        god = sameP ? '偏印' : '正印'
      }
      table[dm][other] = god
    }
  }
  return table
})()

type Polarity = 'Yang' | 'Yin'

export function calcAnnualTransit(bazi: BaziResult, year: number): AnnualTransit {
  // Use Lichun (Feb 4) as the year boundary — get the year's ganzhi from a date well into the year
  const solar = Solar.fromYmdHms(year, 6, 1, 12, 0, 0)
  const ec = solar.getLunar().getEightChar()
  const stemChar = ec.getYearGan()
  const branchChar = ec.getYearZhi()

  const god = TEN_GODS_TABLE[bazi.dayMaster]?.[stemChar] ?? ''

  // Interactions: how does the transit branch interact with each natal branch?
  const natalBranches = [
    bazi.pillars.year.branchChar,
    bazi.pillars.month.branchChar,
    bazi.pillars.day.branchChar,
    bazi.pillars.hour.branchChar,
  ]
  const natalLabels: Pillar['label'][] = ['Year', 'Month', 'Day', 'Hour']

  const transitInteractions: BranchInteraction[] = []

  natalBranches.forEach((nb, i) => {
    // Six harmony?
    for (const [a, b, el] of SIX_HARMONIES) {
      if ((a === nb && b === branchChar) || (b === nb && a === branchChar)) {
        transitInteractions.push({
          type: 'harmony6',
          branches: [nb, branchChar],
          pillars: [natalLabels[i], 'Year (transit)'],
          element: el,
          label: `Transit ${branchChar} harmonizes natal ${natalLabels[i]} ${nb} → ${el}`,
        })
      }
    }
    // Six clash?
    for (const [a, b] of SIX_CLASHES) {
      if ((a === nb && b === branchChar) || (b === nb && a === branchChar)) {
        transitInteractions.push({
          type: 'clash',
          branches: [nb, branchChar],
          pillars: [natalLabels[i], 'Year (transit)'],
          label: `Transit ${branchChar} clashes natal ${natalLabels[i]} ${nb}`,
        })
      }
    }
  })

  // Special stars activated by the transit branch hitting natal positions
  // (i.e. is the transit branch a star in the natal chart's reference frame?)
  const newStars: SpecialStarHit[] = []
  // We just check whether the transit year branch matches any of the user's special-star branches
  for (const star of bazi.specialStars) {
    if (star.branch === branchChar) {
      newStars.push({ starKey: star.starKey, pillar: 'Year', branch: branchChar })
    }
  }

  return {
    year,
    ganZhi: stemChar + branchChar,
    stemChar,
    branchChar,
    stemElement: STEMS[stemChar]?.element ?? 'Earth',
    branchElement: BRANCHES[branchChar]?.element ?? 'Earth',
    god,
    interactions: transitInteractions,
    newSpecialStars: newStars,
  }
}

// ─── Compatibility ───────────────────────────────────────────────────────────

export function calcCompatibility(a: BaziResult, b: BaziResult): CompatibilityResult {
  const aDM = a.dayMasterElement
  const bDM = b.dayMasterElement

  const GENERATES: Record<Element, Element> = { Wood: 'Fire', Fire: 'Earth', Earth: 'Metal', Metal: 'Water', Water: 'Wood' }
  const CONTROLS: Record<Element, Element>  = { Wood: 'Earth', Earth: 'Water', Water: 'Fire', Fire: 'Metal', Metal: 'Wood' }

  let dmRelation = ''
  let dmScore = 50
  if (aDM === bDM) {
    dmRelation = 'Same Element, Friends & Equals'
    dmScore = 70
  } else if (GENERATES[aDM] === bDM) {
    dmRelation = `You nurture them (${aDM} generates ${bDM})`
    dmScore = 85
  } else if (GENERATES[bDM] === aDM) {
    dmRelation = `They nurture you (${bDM} generates ${aDM})`
    dmScore = 85
  } else if (CONTROLS[aDM] === bDM) {
    dmRelation = `You control them (${aDM} controls ${bDM})`
    dmScore = 40
  } else if (CONTROLS[bDM] === aDM) {
    dmRelation = `They control you (${bDM} controls ${aDM})`
    dmScore = 40
  }

  // Branch score: count harmonies (+) and clashes (−) between charts
  const aBranches = [a.pillars.year.branchChar, a.pillars.month.branchChar, a.pillars.day.branchChar, a.pillars.hour.branchChar]
  const bBranches = [b.pillars.year.branchChar, b.pillars.month.branchChar, b.pillars.day.branchChar, b.pillars.hour.branchChar]
  const labelsA: Pillar['label'][] = ['Year', 'Month', 'Day', 'Hour']
  const labelsB: Pillar['label'][] = ['Year', 'Month', 'Day', 'Hour']

  let harmonies = 0
  let clashes = 0
  const crossInteractions: BranchInteraction[] = []

  aBranches.forEach((ba, i) => {
    bBranches.forEach((bb, j) => {
      // Six harmony
      for (const [x, y, el] of SIX_HARMONIES) {
        if ((x === ba && y === bb) || (y === ba && x === bb)) {
          harmonies++
          crossInteractions.push({
            type: 'harmony6',
            branches: [ba, bb],
            pillars: [`A·${labelsA[i]}`, `B·${labelsB[j]}`],
            element: el,
            label: `A's ${labelsA[i]} ${ba} harmonizes B's ${labelsB[j]} ${bb} → ${el}`,
          })
        }
      }
      // Six clash
      for (const [x, y] of SIX_CLASHES) {
        if ((x === ba && y === bb) || (y === ba && x === bb)) {
          clashes++
          crossInteractions.push({
            type: 'clash',
            branches: [ba, bb],
            pillars: [`A·${labelsA[i]}`, `B·${labelsB[j]}`],
            label: `A's ${labelsA[i]} ${ba} clashes B's ${labelsB[j]} ${bb}`,
          })
        }
      }
    })
  })

  // Day branch direct match is a special highlight
  const dayMatchHarmony = SIX_HARMONIES.some(([x, y]) =>
    (x === a.pillars.day.branchChar && y === b.pillars.day.branchChar) ||
    (y === a.pillars.day.branchChar && x === b.pillars.day.branchChar)
  )
  const dayClash = SIX_CLASHES.some(([x, y]) =>
    (x === a.pillars.day.branchChar && y === b.pillars.day.branchChar) ||
    (y === a.pillars.day.branchChar && x === b.pillars.day.branchChar)
  )

  // Branch score: base 50 + harmonies − clashes, day pillar weighted
  let branchScore = 50 + harmonies * 6 - clashes * 8
  if (dayMatchHarmony) branchScore += 15
  if (dayClash) branchScore -= 20
  branchScore = Math.max(0, Math.min(100, branchScore))

  // Element complementarity: how well do the two element profiles fill each other's gaps?
  // For each element, take A's % and B's %; reward when their average is closer to 20% (balanced)
  let complementSum = 0
  for (const el of ['Wood','Fire','Earth','Metal','Water'] as Element[]) {
    const avg = (a.elementPercent[el] + b.elementPercent[el]) / 2
    const distance = Math.abs(avg - 20)  // 20% = perfect
    complementSum += Math.max(0, 30 - distance) // each element contributes 0-30
  }
  const elementScore = Math.min(100, Math.round((complementSum / 150) * 100))

  // Overall: weighted average
  const overallScore = Math.round(
    dmScore * 0.4 +
    branchScore * 0.4 +
    elementScore * 0.2
  )

  const notes: string[] = []
  notes.push(dmRelation)
  if (dayMatchHarmony) notes.push('Day Pillar Harmony, natural soulmate resonance.')
  if (dayClash)        notes.push('Day Pillar Clash, fundamental friction in core values.')
  if (harmonies >= 3)  notes.push(`${harmonies} branch harmonies, strong overall flow.`)
  if (clashes >= 3)    notes.push(`${clashes} branch clashes, significant turbulence.`)
  if (elementScore > 75) notes.push('Element profiles complement each other well, you balance each other.')
  if (elementScore < 40) notes.push('Element profiles are misaligned, both lack or overflow in similar areas.')

  return {
    dayMasterRelation: dmRelation,
    dmScore,
    branchScore,
    elementScore,
    overallScore,
    notes,
    interactions: crossInteractions,
  }
}

// Quick lookup: just the year animal from a date (used for simple displays)
export function getYearAnimal(year: number, month: number, day: number): string {
  const solar = Solar.fromYmd(year, month, day)
  const ec = solar.getLunar().getEightChar()
  return BRANCHES[ec.getYearZhi()]?.animal ?? ''
}

// Re-export the ELEMENT_MAP for any UI needing it
export { ELEMENT_MAP }
