// ─── Complete Numerology Interpretations ──────────────────────────────────────
// Tone: direct, psychologically grounded. No new-age language.

// ─── Interfaces ───────────────────────────────────────────────────────────────

export interface NumberInterpretation {
  meaning: string
  positive: string[]
  shadow: string[]
  advice: string
  career: string
  love: string
  money: string
  archetype: string
}

export interface NumberDetail {
  general: string
  lifePath: string
  expression: string
  soulUrge: string
  personality: string
  birthDay: string
  strengths: string[]
  weaknesses: string[]
  advice: string
}

export interface Interpretations {
  numbers: Record<number, NumberDetail>
  combinations: Record<string, string>
  pinnacles: Record<number, string>
  challenges: Record<number, string>
  lifeCycles: Record<number, string>
  personalYears: Record<number, string>
}

// ─── Main interpretations object ─────────────────────────────────────────────

export const interpretations: Interpretations = {

  // ── Numbers 1–9, 11, 22, 33 ─────────────────────────────────────────────────

  numbers: {

    1: {
      general: "The 1 is defined by its relationship to autonomy, often at any cost. People with strong 1 energy need to be the originator, the decision-maker, the one who sets direction. This isn't narcissism, though it can look like it: it's a deep discomfort with being at the mercy of someone else's choices. The strength is genuine initiative and decisiveness; the shadow is an inability to delegate, ask for help, or tolerate being corrected. When life doesn't give a 1 sufficient agency, through controlling relationships, bureaucratic structures, or external constraints, the energy converts to frustration, rigidity, or low-grade chronic anger. The central developmental task is learning that needing others doesn't disqualify you from being who you are.",
      lifePath: "Your life is organized around the question of independence. Expect situations that repeatedly force you to choose between controlling outcomes and staying connected to people. Early challenges may push you into leadership before you've developed the emotional range for it. The work isn't to become less assertive, it's to learn that real strength includes being wrong sometimes and adjusting without collapse.",
      expression: "Your natural mode is initiation, you're built to start things, not maintain them. You communicate through action more than language. At your best, you're the person who moves when others freeze. The risk: you steamroll slower processors and interpret collaboration as friction. You need to actively develop patience with the pace of other people.",
      soulUrge: "At the core, you want self-sufficiency, not wealth or recognition for their own sake, but the specific freedom of not needing rescue. This shapes your aversion to bureaucracy, your resistance to asking for help, your preference for operating alone. The drive is legitimate. The problem is that it creates unnecessary isolation and prevents you from building the alliances that would actually give you more leverage.",
      personality: "From the outside you read as confident, sometimes blunt, occasionally intimidating. People either follow your lead or push back hard, there's rarely neutrality. You project certainty even when you don't feel it, which is a useful social tool but also a mask you can get trapped behind. Others may not realize you doubt yourself as often as you do.",
      birthDay: "Born on a day reduced to 1, you have a native instinct for self-direction that showed up early, probably as a child who had firm ideas about how things should go. This isn't stubbornness for its own sake; it's a legitimate drive toward self-definition. The developmental work is separating self-direction from isolation.",
      strengths: ["Decisive under pressure without needing consensus", "Genuine initiative, starts things others only talk about", "Clear directional sense, hard to manipulate"],
      weaknesses: ["Difficulty receiving help without feeling diminished", "Impatience with others' pace and process", "Mistakes stubbornness for conviction"],
      advice: "Interdependence is not a character flaw. Your capacity to act alone is a tool, use it when it serves, not as proof of something. Identify one area this year where you're refusing help out of ego rather than competence, and change that deliberately.",
    },

    2: {
      general: "The 2 operates through attunement, a constant, often involuntary reading of the room, sensing what others need and adjusting accordingly. At its best this produces genuine empathy and diplomatic skill. At its worst, it produces a person who can't locate their own position because they're perpetually accommodating everyone else's. The central shadow is that the harmony a 2 creates is sometimes false: agreements made not because everyone aligned, but because the 2 found it unbearable to hold the tension. Passive aggression is a common outlet, when direct confrontation feels impossible, resentment accumulates beneath the surface and expresses sideways. People with strong 2 energy often underestimate their own influence because they've spent so long making others feel like the originator.",
      lifePath: "Your life is structured around relationships, not romantic ones exclusively, but all forms of connection. You will be tested through the question of where your needs end and other people's begin. Situations will arise that require you to hold a position others dislike, and the discomfort you feel in those moments is the curriculum. Real cooperation requires two distinct people, not one person dissolving into another.",
      expression: "You work best as the person who builds the bridge, between conflicting parties, between an idea and its execution, between a vision and the people who can carry it. Your talent isn't in the spotlight; it's in making the spotlight possible for others. This is not a lesser function. The risk is undervaluing what you do because it doesn't come with obvious credit.",
      soulUrge: "What you want most is to matter to someone specific, to be genuinely needed, not as a function but as a person. When this need isn't acknowledged, you tend to work harder at accommodation, trying to earn what should be given freely. You need partners and friends who name what you bring, not just assume it.",
      personality: "Others experience you as approachable, warm, attentive. You remember things about people that they barely remember themselves. The risk is that your warmth reads as compliance, and some people will take advantage. You may need to develop a harder social surface than comes naturally, not to become cold, but to protect the real warmth underneath.",
      birthDay: "Born on a day reduced to 2, your native sensitivity operates as both gift and vulnerability. You process social information quickly, often too quickly, acting on impressions before examining them. Learning to slow down between what you sense and what you do about it is the key developmental work.",
      strengths: ["Exceptional attunement to others' states", "Real diplomatic skill based on genuine care", "Capacity for sustained, patient collaboration"],
      weaknesses: ["Difficulty locating and defending your own position", "Creates false harmony through premature agreement", "Passive aggression when direct conflict feels impossible"],
      advice: "Your ability to read rooms is a skill, not a moral obligation. You are not required to make every situation comfortable. Practice stating a preference directly, not as a request for permission, but as a simple fact, at least once a day.",
    },

    3: {
      general: "The 3 is the number of expression, and its essential question is: what are you actually saying? People with strong 3 energy have a genuine creative gift, for language, image, humor, connection, but that gift can become a defense mechanism, a way of keeping things light enough that nothing has to be examined too closely. The 3 at its best produces artists and communicators who make difficult things accessible. The 3 at its worst produces a person who mistakes entertainment for communication, charm for depth, and momentum for purpose. Scattered focus is the signature problem: too many interests, projects started and abandoned, relationships kept at a comfortable emotional distance through wit and performance.",
      lifePath: "Your life is built around the question of what you actually have to say, not what's clever or well-received, but what's true. You will accumulate gifts and interests naturally; the work is learning to focus them. Expect periods of creative output followed by complete dissipation. The lesson isn't to eliminate the fallow periods but to stop mistaking activity for progress.",
      expression: "You are built to communicate, writing, speaking, visual work, music. The medium almost doesn't matter. What matters is that when 3 energy is channeled through real discipline, the output can be extraordinary. The problem is that discipline is exactly what most 3s resist. You'll need structure you didn't choose yourself, which is uncomfortable but necessary.",
      soulUrge: "Underneath the social ease and creative range, what you want is to be genuinely seen, not applauded, but recognized. The performance is partly a test: will you still value me if I'm not entertaining? Most 3s never ask this question directly. Instead, they keep performing, hoping someone will see through it. Stop performing with the people you actually care about.",
      personality: "You're experienced as bright, funny, easy to be around. People enjoy your company. The risk is that the ease becomes a surface, that others never feel they've met the real person beneath the charm. Depth, not additional charm, is what will create the relationships you actually want. Let people see you in your less impressive moments.",
      birthDay: "Born on a day reduced to 3, you have native fluency in expression, words, ideas, social navigation come easily. This fluency can be a trap: you coast on facility long past the point where you should be developing genuine mastery. The developmental question is where you're willing to work when it stops being fun.",
      strengths: ["Genuine creative range across multiple domains", "Natural communicator who can read audiences", "Optimism that is sometimes actually warranted"],
      weaknesses: ["Scattered attention across too many directions at once", "Charm deployed as emotional avoidance", "Difficulty tolerating the tedium required for real mastery"],
      advice: "Choose one medium and stay with it long enough for the discomfort to become information rather than a signal to quit. Your creative range is an asset only if one thing goes deep. Surface width isn't enough.",
    },

    4: {
      general: "The 4 is the number of structure, and the question it keeps running into is: when does structure serve the work, and when does it become a way of avoiding uncertainty? People with strong 4 energy have a genuine gift for systems, reliability, and patience, they can build things that last. But the shadow is rigidity: an aversion to ambiguity so strong that it prevents adaptation when the plan stops working. There's often an implicit belief that following the rules, working hard, being responsible, doing it right, will eventually be rewarded, and deep frustration when it isn't. The 4 is not a naturally lucky energy. What it offers is solidity, not ease.",
      lifePath: "Your life is built on the question of what you're actually building and whether it will stand. Expect the work to be harder than it seems it should be. Obstacles aren't signs you're on the wrong path, they're the terrain. The lesson is not just persistence but flexibility: the ability to revise the plan without abandoning the goal.",
      expression: "You are built for execution. Where others generate ideas, you make them concrete, working out the actual steps, the timeline, the resource requirements. This is enormously valuable and consistently undervalued in environments that prize novelty over function. The risk: you become so focused on method that you lose sight of purpose.",
      soulUrge: "What you want, at depth, is security, not luxury, but stability: a world where effort reliably produces results, where the ground doesn't move. This desire is legitimate and often disappointed. Life is structurally less ordered than the 4 would prefer. The developmental task is finding peace with uncertainty without abandoning the discipline that is genuinely yours.",
      personality: "Others experience you as reliable, serious, competent, the person they come to when something needs to actually get done. The risk is coming across as rigid or joyless, not because you are those things, but because you prioritize substance over presentation. Communicating warmth more explicitly will help, not compromise you.",
      birthDay: "Born on a day reduced to 4, you have a native seriousness and capacity for sustained effort that most people lack. The risk is taking on too much responsibility too early, becoming the structural support for family or organization before you've built your own foundation. Your reliability can be exploited. Learn to ration it.",
      strengths: ["Exceptional follow-through on complex, long-term commitments", "Genuine patience with slow, multi-step processes", "Reliability that others can actually depend on, rare quality"],
      weaknesses: ["Rigidity when the plan stops working", "Difficulty delegating because no one does it quite right", "Equates hard work with virtue regardless of whether the work is in the right direction"],
      advice: "Effort is not the same as progress. You can work harder than anyone and still be building the wrong thing. Periodically evaluate whether your structure is serving the goal or whether you've started serving the structure. Revise before you're forced to.",
    },

    5: {
      general: "The 5 is the number of change, and its central tension is between the freedom it craves and the rootedness it needs. People with strong 5 energy have a genuine gift for adaptability, for reading rapidly changing situations, for connecting with diverse people. But the shadow is restlessness that mistakes motion for progress: the next city, the next relationship, the next project, always before the previous one has been brought to completion. There is often an unconscious avoidance of the depth that comes only with staying, the knowledge that accumulates in a relationship after the first year, the mastery that comes after two thousand hours, the trust built over decades. The 5 tends to leave before the real work begins.",
      lifePath: "Your life is structured around the question of what you're actually free for, freedom without direction is just drift. Expect periods of expansion followed by reckoning: you will at some point need to choose depth over range. The lesson isn't to become less adventurous; it's to develop the discipline that gives adventure actual direction.",
      expression: "You are built for variety, multiple domains, shifting roles, constant cross-pollination of ideas. At your best you make unusual connections that specialists miss. The risk: you're useful in the early stages of everything and unreliable in the middle stages. Develop the ability to push through the difficult middle of a project, when novelty has worn off, because that's where real output is produced.",
      soulUrge: "What you want most is the feeling that options remain open. Commitment, long-term obligation, routines, these feel like walls, even when you've chosen them. The deeper truth is that the freedom you're protecting is partly an avoidance of the vulnerability that comes with sustained investment. Real freedom isn't the absence of commitment; it's choosing the right ones.",
      personality: "Others experience you as dynamic, interesting, exciting to be around. You attract people easily. The risk is that people learn not to count on you for sustained support, because you've conditioned them not to. You may be well-liked by many and deeply known by almost none. If that bothers you, and it probably does, the solution isn't more contact, it's deeper contact.",
      birthDay: "Born on a day reduced to 5, you have a native capacity for improvisation and change. The world's unpredictability reads less like threat and more like information. But this facility can mask a lack of developed preferences, you adapt so well that you sometimes can't locate what you actually want versus what seems available.",
      strengths: ["Genuine adaptability in unpredictable situations", "Ability to connect with very different kinds of people", "Comfort with uncertainty that others find paralyzing"],
      weaknesses: ["Avoidance of depth through constant movement", "Unreliable in the sustained middle of long commitments", "Mistakes stimulation for meaning"],
      advice: "Choose one thing that matters and stay with it past the point of novelty. There are specific kinds of knowledge that only come with time. You're missing them. Pick something and find out what's on the other side of the difficult middle.",
    },

    6: {
      general: "The 6 is the number of responsibility, and its central problem is the confusion between genuine care and control through service. People with strong 6 energy have a real capacity for nurturing, they see what others need and often provide it without being asked. But the shadow is a form of management disguised as love: making themselves indispensable, creating a structure of dependence that confirms their own sense of purpose. The 6 often knows what's best for people close to them, and may even be right, but imposes this knowledge in ways that undermine others' autonomy. The question the 6 needs to sit with: am I helping because it's genuinely needed, or because I can't tolerate watching someone else struggle?",
      lifePath: "Your life is structured around relationships and responsibility, not just family, but your extended sense of who you're accountable to. Expect recurring situations where you're asked to take on more than your fair share, because you'll say yes more readily than others. The developmental task is learning to let problems be someone else's to solve, even when you could fix them faster.",
      expression: "You're built to support and develop others, teaching, counseling, creating environments where people function well. At your best, you make things better for everyone around you. The risk: you become so essential to others' functioning that you have no life outside of maintenance. Your creative energy needs its own outlet, separate from your service function.",
      soulUrge: "What you want at depth is harmony, not peace as the absence of conflict, but the specific warmth of everyone being okay. When people around you are in difficulty, you can't settle. This drive is genuinely care-based, but it also has a self-interested element: their distress activates your distress, and helping is partly management of your own discomfort. Noticing this doesn't make you selfish. It makes you more effective.",
      personality: "Others experience you as warm, dependable, the person who shows up. People bring you their problems because they trust you'll engage seriously. The risk: over time you accumulate everyone else's weight without anyone noticing you're carrying it. Set limits not because you stop caring but because unlimited availability breeds dependency and erodes you.",
      birthDay: "Born on a day reduced to 6, you have a native sense of obligation to people around you that activated young, probably taking on emotional labor in your family before you understood the cost. This pattern of early responsibility shapes your relationship to service. The work is choosing service rather than being conscripted into it.",
      strengths: ["Genuine sustained care for others' wellbeing", "Strong sense of responsibility that people can actually rely on", "Eye for what environments and relationships need to function well"],
      weaknesses: ["Control through service, helping as management of others", "Difficulty tolerating others' autonomy to make their own bad choices", "Accumulates responsibility until collapse"],
      advice: "Next time someone has a problem you know how to solve, wait before offering. Let them ask. Notice whether the impulse to help is about them or about your discomfort watching them struggle. This isn't callousness, it's the beginning of respecting people as capable of navigating their own lives.",
    },

    7: {
      general: "The 7 is the number of inquiry, and its central challenge is the difference between genuine investigation and intellectualized withdrawal. People with strong 7 energy have a real analytic gift, they think carefully, don't accept easy answers, and are often right. But the shadow is superiority disguised as discernment: holding the world at arm's length behind a screen of analysis, remaining the observer rather than participant, using the standards of their thinking as a reason not to engage with anything or anyone who doesn't meet them. Intimacy is the specific problem area, not because 7s don't feel, but because being genuinely known requires exposure that analysis can't protect you from.",
      lifePath: "Your life is structured around the question of what you actually believe when you've done the work of figuring it out. Expect periods of intense focus followed by doubt about whether the focus was on the right thing. The lesson isn't to become less rigorous, it's to eventually commit to something you've investigated long enough, rather than always remaining in the inquiry phase.",
      expression: "You're built for specialized depth, research, analysis, mastery of a narrow domain done thoroughly. Your output at its best carries a quality of precision that generalists can't produce. The risk: you spend so long investigating that you never publish, perform, or put the work in front of an audience that could be changed by it. At some point, the inquiry has to become output.",
      soulUrge: "What you want most is to understand, not to accumulate information, but to grasp how something works at a structural level. This can make you an exceptional thinker and a maddeningly slow decision-maker, because you're always aware of what you still don't know. At some point, sufficient information is enough. Waiting for certainty is often avoidance of commitment.",
      personality: "Others experience you as intelligent, self-contained, sometimes remote. You're not unfriendly, but social energy has a cost for you that it doesn't for others, and people sense that. The risk is that your reserve is misread as arrogance or disinterest, when it's neither. Some minimal expenditure of social warmth protects you from unnecessary misunderstanding.",
      birthDay: "Born on a day reduced to 7, you have a native relationship with your own interior that is more detailed than most people's. You notice things, about yourself, about situations, that others walk past. The risk is that this self-awareness becomes self-consciousness: so aware of your own processes that you can't act without analyzing the action.",
      strengths: ["Genuine rigor, doesn't accept easy or convenient answers", "Capacity for sustained focused inquiry that produces real expertise", "Pattern recognition that operates below the social surface"],
      weaknesses: ["Uses analysis to defer commitment and emotional exposure", "Can be quietly contemptuous of people who think less carefully", "Gets lost in the inquiry and forgets to produce anything from it"],
      advice: "Pick something you've been investigating long enough and take a position. Say it, publish it, commit to a conclusion that might be wrong. The quality of your thinking is not protected by withholding it, it's only tested by putting it into the world where it can be challenged.",
    },

    8: {
      general: "The 8 is the number of power, and its central challenge is the difference between legitimate authority and domination. People with strong 8 energy are genuinely ambitious, they think in terms of scale, leverage, long-term position. At its best, the 8 produces people who build things that outlast them, who take real risks for real stakes. The shadow is the need to win even when winning costs too much, relationships damaged in the pursuit of an outcome that turned out not to be worth it, trust burned for the sake of leverage. The 8 can be ruthlessly pragmatic in a way that is efficient in the short term and corrosive over time.",
      lifePath: "Your life is structured around questions of power, not always consciously, but the recurring theme will be who controls what and whether you have sufficient influence over your own circumstances. Expect significant material challenges and significant material opportunities; this is one of the numbers where the relationship to money and authority needs to be actively negotiated, not avoided.",
      expression: "You're built for execution at scale, management, strategic planning, building organizations or systems with significant resources. Your natural mode is authority. The risk: you can be effective in the narrow sense while being destructive in the broader one, achieving the goal while losing the team. Sustainable 8 energy requires developing people, not just using them.",
      soulUrge: "What you want at depth is impact, the ability to shape outcomes at a scale that matters. This isn't inherently corrupting, but it becomes so when decoupled from purpose. Power as an end in itself produces increasingly hollow achievement. The question the 8 needs to return to regularly: what is the power actually for?",
      personality: "Others experience you as formidable, decisive, sometimes overwhelming. You carry authority naturally, which means people often defer to you whether you've earned it in a given situation or not. This makes it harder to get honest feedback, people tell you what you want to hear. Actively creating conditions where people can push back is intelligence, not weakness.",
      birthDay: "Born on a day reduced to 8, you have a native relationship with resource and authority that manifested early. You likely had strong opinions about fairness and power as a child, what belongs to whom, who has the right to decide. This sensitivity to power dynamics is an asset when consciously used.",
      strengths: ["Genuine strategic intelligence, sees leverage others miss", "Capacity for the sustained ambitious work required to build at scale", "Comfort with authority and high stakes that most people find destabilizing"],
      weaknesses: ["Can be ruthless in ways that are efficient short-term and corrosive long-term", "Difficulty tolerating being wrong in front of others", "Power becomes an end rather than a means"],
      advice: "Map the wreckage behind your recent wins, not to punish yourself, but to get accurate. High-achieving 8s often leave a trail of burned relationships they never had to directly confront because they moved on quickly. The bill comes eventually. Pay attention to who isn't returning your calls.",
    },

    9: {
      general: "The 9 is the number of completion, and its central tension is between the universal compassion it genuinely feels and the personal grief it can never quite finish processing. People with strong 9 energy have a real capacity for empathy at scale, they care about the large picture, the collective, the long arc. But this universal orientation is sometimes a flight from the specific: from the particular wound, the specific person who hurt them, the loss that never got mourned. The 9 tends to skip over its own pain in the name of a larger purpose, and that pain finds other outlets, idealism that becomes bitterness when the world doesn't cooperate, generosity that cracks under accumulated resentment.",
      lifePath: "Your life is structured around the question of what you're actually letting go of, not philosophically, but specifically. Completion means closing what needs closing: relationships, phases, beliefs that have outlived their use. Expect recurring situations where you're asked to release something before you feel ready. Readiness is rarely the condition; the ending is the teacher.",
      expression: "You're built for synthesis, taking in wide experience and producing something that addresses more than the personal. Teaching, writing, counseling, activism: natural expressions of 9 energy. The risk: the ambition of your scope prevents completion. Something addressed to everyone lands with no one. Specificity, paradoxically, is how the universal gets transmitted.",
      soulUrge: "What you want at depth is to matter, not to a specific person, but to the world, to history, to a cause larger than yourself. This is a legitimate desire that can produce remarkable work. The shadow: when the large purpose isn't going well, there's no smaller circle to fall back on. You need specific close relationships as well as the broad mission, not instead of them.",
      personality: "Others experience you as wise, tolerant, a little otherworldly. You give people the sense that you've seen more than they have and aren't shocked by much. The risk: you can be so tolerant that people don't experience any real friction with you, no pushback, no stated limits, and they begin to wonder whether you're actually present. Discernment isn't coldness. Use it.",
      birthDay: "Born on a day reduced to 9, you have a native quality of perspective, the ability to zoom out from the immediate situation to the longer pattern. This is useful. The risk is using perspective as a way to avoid being affected by what is directly in front of you. Some things should affect you. Let them.",
      strengths: ["Genuine wide-angle empathy that isn't performance", "Capacity to synthesize disparate experience into something coherent", "Tolerance of complexity and contradiction without premature resolution"],
      weaknesses: ["Avoids personal grief through universal concern", "Idealism that converts to bitterness when disappointed by the world", "Difficulty maintaining close relationships alongside large-scale commitments"],
      advice: "Identify the specific thing, the person, the event, the loss, that you've been addressing symbolically through your larger work. Bring it into direct contact. Not to therapize it, but to give it its proper proportion rather than letting it run everything from underneath.",
    },

    11: {
      general: "The 11 is a master number, intensified 2 energy with an additional dimension of sensitivity that is a genuine asset and a genuine burden. People with 11 as a core number receive impressions at a volume others don't: emotional cues, atmosphere, subtle dynamics. This produces both unusual perceptive ability and chronic overstimulation. The specific trap of the 11 is the gap between perception and action: you can see what needs to happen with unusual clarity, but the nervous system cost of operating in the world can make consistent action feel out of reach. When 11s collapse into their 2 shadow, they become passive, people-pleasing, and exhausted. The work is building the structures that support and protect the perception so it can produce.",
      lifePath: "Your life is structured around the challenge of channeling unusually high sensitivity into coherent work. Expect periods of remarkable clarity followed by complete shutdown, the nervous system requires more recovery time than average. The lesson is not to eliminate the sensitivity, which is your actual gift, but to build the structures that protect it so it can produce consistently.",
      expression: "You're built to translate what you perceive into forms others can access. The depth of your perception is real; the challenge is the technical development required to express it precisely. Many 11s have the vision without the craft because craft requires the sustained repetitive work their system resists. The craft is not optional, it's how the perception reaches anyone.",
      soulUrge: "What you want at depth is to bridge something, to take what you sense and make it real for others, to close the gap between the way things are and how they could be. This is a genuine aspiration, not fantasy. But it requires operating in the physical world with its demands of form, time, and imperfect conditions. The bridge has to be built from both sides.",
      personality: "Others often experience you as unusually perceptive, sometimes uncanny. People may feel seen by you before you've said much. This can attract people deeply and create unrealistic expectations, you get assigned the role of the wise one before you've had time to be wrong. Protect against the projection of guru status; it's a trap that isolates and eventually collapses.",
      birthDay: "Born on a day reduced to 11, your native perception is high-resolution in ways that can be disorienting, particularly in environments with a lot of sensory or emotional noise. You likely developed strong filtering mechanisms early, ways to manage the incoming signal. The work is calibrating those filters rather than maxing them out.",
      strengths: ["Perception at a level of detail that produces genuine insight", "Capacity for bridging, translating complex inner states into accessible form", "Sensitivity that, when grounded, becomes a precision instrument"],
      weaknesses: ["Chronic overstimulation that makes sustained action difficult", "Collapses into 2 shadow: passive, people-pleasing, exhausted", "Perception without output, sees clearly but doesn't act on it"],
      advice: "The sensitivity is real and so are its costs. Stop trying to eliminate the costs and start designing your life to accommodate them: less noise, more recovery time, deliberate limits on social demand. Not self-indulgence, engineering. Then use what you sense to produce something.",
    },

    22: {
      general: "The 22 is a master number, intensified 4 energy aimed at building something of genuine scale. People with 22 as a core number have a real capacity for large-scale vision combined with the practical intelligence to execute it, an unusual combination. The specific trap of the 22 is the gap between the scale of the vision and the willingness to do the slow, granular work required to realize it. The burden of potential is also real: the sense that you're supposed to build something significant can be paralyzing rather than motivating. Many 22s either collapse into 4 shadow, rigid, limited, workaholic without direction, or spend years generating impressive-sounding plans that never reach completion.",
      lifePath: "Your life is structured around the question of what you're actually building and whether it will outlast you. The scale of the work you're here for is genuinely larger than average, this is not inflation, it's the actual terrain. But the gap between vision and reality is filled with boring, difficult, repetitive work that the 22's temperament often resists. The vision without the execution is nothing.",
      expression: "You're built for large-scale coordination, bringing together people, resources, systems, and time horizons in service of something significant. The risk: the complexity you can hold in your head is greater than most people's, which makes delegation painful. You see what they're missing. But you cannot do it alone, and the attempt to do so is the most common way 22s fail.",
      soulUrge: "What you want at depth is legacy, something that justifies the scale of your ambition by actually mattering beyond yourself. The risk: the pursuit of significance becomes its own obstacle, too concerned with whether the work is large enough to commit to the specific work actually in front of you. Significance is usually built from unremarkable daily decisions.",
      personality: "Others experience you as capable and serious, someone who operates at a different scale. This can inspire or intimidate depending on the person. The weight of potential you carry is often visible, and people either want to be part of it or feel implicitly inadequate around it. Neither reaction is your responsibility to manage.",
      birthDay: "Born on a day reduced to 22, you have a native capacity for holding complexity that showed up early, probably as a child who saw systems and structures that others treated as fixed. The developmental task is converting that perception into patient, sustained construction rather than restless generation of new visions every few years.",
      strengths: ["Rare combination of large-scale vision and practical intelligence", "Capacity to hold complexity across extended time horizons", "Genuine ability to organize and build at the scale that matters"],
      weaknesses: ["Paralysis under the weight of potential, too aware of what's possible to commit to what's specific", "Collapses into 4 shadow: rigid, workaholic, limited in scope despite the ambition", "Difficulty delegating because no one can see quite what you see"],
      advice: "Choose the specific project, not the category, not the field, but the actual thing with its actual constraints. The 22 tends to operate indefinitely at the level of the possible. Pick one thing, however imperfect, and build it to completion. That completion will teach you more than any further planning.",
    },

    33: {
      general: "The 33 is a master number, intensified 6 energy at the level of universal service. People with 33 as a core number have a real capacity for compassion and healing, and a corresponding vulnerability to martyr dynamics. The 33 shadow is self-erasure disguised as service: an inability to maintain limits because maintaining them feels selfish against the background of others' suffering. The specific trap is the belief that your needs can wait, that once everyone else is sorted, there will be space for you. There will not be. People always need something. The 33 must build self-sustaining practices into their life before the demand becomes overwhelming, not after.",
      lifePath: "Your life is structured around the question of how to serve without being consumed. Genuine 33 energy at its highest expression is extraordinary, the teacher, the healer, the presence that changes rooms. But the path to that expression requires a degree of self-knowledge and self-protection that is genuinely difficult, because the 33's instinct is always to redirect attention toward others.",
      expression: "You're built to nurture at scale, to hold space, teach, guide, heal in ways that ripple beyond the immediate relationship. At your best, what you do for one person becomes a model for how that person treats others. The risk: you give so thoroughly that there is nothing left of your own creative or personal life. That depletion is not virtuous, it's a failure of sustainability.",
      soulUrge: "What you want at depth is for people to be okay, specifically the people closest to you, and more broadly the world. This desire is real and it is also partially a response to your own early experiences of others not being okay. Healing the world and healing yourself are related projects. Don't treat them as separate.",
      personality: "Others experience you as compassionate, steady, the person who doesn't flinch from difficulty. People sense they can bring their real problems to you. The risk: you become the container for everyone else's disorder without anyone doing that for you. Build one or two relationships in which you are the one being held, not the one holding.",
      birthDay: "Born on a day reduced to 33, you have a native orientation toward others' wellbeing that was probably visible in early childhood. The developmental work is not eliminating this orientation but preventing it from being the only organizing principle of your life.",
      strengths: ["Genuine capacity for sustained compassion that doesn't burn out quickly", "Healing presence, changes the quality of environments and relationships", "Rare ability to hold others' complexity without judgment"],
      weaknesses: ["Self-erasure disguised as service, gives until there is nothing left", "Inability to set limits without experiencing them as failure", "Accumulates others' suffering until collapse"],
      advice: "Write down your own needs, not your preferences, your actual needs. Then identify how many are currently being met. A 33 who has collapsed is useful to no one. Build the self-sustaining infrastructure first, then serve from the surplus.",
    },

  },

  // ── Life Path × Expression combinations ──────────────────────────────────────

  combinations: {

    // Life Path 1
    "1-1": "Two independent operators in the same life. Your pattern is self-sufficiency squared: high drive, high output, high resistance to anything that feels like constraint. The risk is that everything defaults to competition, with others, with yourself, with the situation. You need to win, and when life doesn't allow it, the energy turns inward as frustration or outward as aggression. Learn to distinguish genuine autonomy from reflexive resistance to being told what to do. Not every direction from someone else is a threat to your independence.",
    "1-2": "Your life path drives toward independence while your expression naturally seeks connection and collaboration. This creates genuine internal friction: the pioneer who also deeply needs relationship. The risk is oscillating between dominance and accommodation, leading boldly, then over-adjusting to keep others comfortable. The integration required is asserting yourself clearly while staying genuinely curious about other perspectives. Neither fully dissolves for the other.",
    "1-3": "Your life path asks for direction and your expression generates creativity. At your best, you produce original work with conviction. At your worst, you scatter brilliant starts across multiple domains without bringing any to completion. The specific challenge: your 3 expression wants freedom and approval while your 1 path demands discipline and independence. These can work together, but only if the creative energy is focused by consistent, unglamorous effort.",
    "1-4": "Your drive toward independence meets an expression built for structure and execution. This is potentially powerful, the initiator who can also build. The risk is rigidity: your 4 expression can turn the 1's directional energy into inflexibility. You know what you're building and how you're building it, and deviation from either feels like failure. Develop tolerance for necessary changes in method even when the goal stays fixed.",
    "1-5": "Your independence-oriented life path meets an expression built for movement and variety. This combination can produce a genuinely dynamic person, someone who initiates boldly and adapts quickly. The shadow: neither the 1 nor the 5 are built for the patient middle of long commitments. You start strong, adapt when needed, and tend to exit before completion. Develop the discipline to stay past the point where things stop being interesting.",
    "1-6": "Your independence-oriented life path meets a 6 expression wired to take responsibility for others. The internal conflict is real: you want to operate without constraints, but your natural expression is to take on others' burdens. Watch for the pattern where you build something, a business, a family structure, a team, and then feel trapped by it. Deliberately choose which responsibilities you take on rather than accumulating them by default.",
    "1-7": "Your life drives you toward independence while your expression moves through analysis and interior depth. You are probably difficult to read and harder to argue with: direct in your path but rarely showing your full reasoning. The risk is that your 7 expression becomes a justification for the 1's preference for solitude, every potential connection assessed for its worth and usually found lacking. Let people in before the analysis is complete.",
    "1-8": "Power doubled: your life path demands independence and your expression moves through authority and resource. This combination can build empires, but the shadow is correspondingly large. The need to control outcomes is very high, and the tolerance for being wrong or outmaneuvered is very low. You probably leave behind people who felt used rather than developed. That cost is real and accumulates. Sustainable 1-8 energy requires learning to see the people around you as ends, not means.",
    "1-9": "Your life drives you toward independence while your expression is oriented toward the collective. The individual autonomy drive meets the selfless service drive. At your best, you build something genuinely your own that also serves a larger purpose. At your worst, you're either lost in abstract concern for everyone while failing specific people, or so focused on your own path that the larger dimension never gets expressed.",

    // Life Path 2
    "2-1": "Your life is built around relationship and cooperation, but your expression leads with directness and independence. People experience you as a collaborator who also has a strong point of view, which is actually an asset, though it can confuse people who expected pure accommodation. The shadow: when cooperation fails, you can overcorrect into dominance. When that doesn't work, you swing back to passive accommodation. The middle path is stating your view clearly while remaining genuinely open to being changed by it.",
    "2-2": "Sensitivity doubled. You attune to others with unusual precision, producing both genuine empathy and real vulnerability to other people's emotional states. The boundary question is central to everything in your life: where you end and others begin. You probably don't have a clear answer to this, and that gap is the source of most of your relational difficulty. Your needs are not less important because you're good at meeting everyone else's.",
    "2-3": "Your relational life path meets a creative, communicative expression. At best, you communicate with unusual emotional intelligence, your work knows what the audience is feeling before it does. The risk: the 3 expression uses charm to avoid the depth the 2 path requires. You can keep things light and enjoyable when the relational curriculum is asking for vulnerability. Choose depth over ease in the connections that matter.",
    "2-4": "Your relational life path meets a structured, practical expression. This combination can make good relationships reliable, you don't just feel connection but maintain it through consistent behavior. The shadow is treating relationships like projects: structured, managed, maintained on schedule. The feeling gets lost in the system. Make space for the unplanned moment, the conversation that goes nowhere in particular and means everything.",
    "2-5": "Your life path asks for relational depth and sustained connection, while your expression is wired for freedom and variety. The 5 expression resists exactly what the 2 path requires. You may repeatedly enter deep connection and then need to leave before it becomes confining. The integration: develop a form of freedom that includes sustained commitment, which is possible, but it requires honest examination of what specifically feels confining and why.",
    "2-6": "Relational sensitivity combined with strong responsibility orientation. You feel others deeply and feel responsible for them. The shadow: you carry the emotional weight of everyone close to you while systematically neglecting to advocate for your own needs. 'I'm fine' is probably used more often than it's accurate. Build in regular explicit conversations about what you need, not as complaint, but as information the people close to you require.",
    "2-7": "Your relational life path meets an interior, analytic expression. You navigate the world through sensing and through thinking, often simultaneously, and the two systems don't always agree. You may be excellent at reading situations and then second-guessing the read with analysis. Trust the initial perception more. Your sensing is calibrated; your analysis sometimes pathologizes it.",
    "2-8": "Your cooperative life path meets a powerful, ambitious expression. Your attunement helps you understand what others need while your expression gives you tools to build something significant. The shadow: as you build power, the relational sensitivity can become an inconvenience rather than an asset. You may start managing where you used to care. Protect the care. It's what makes you worth working with.",
    "2-9": "Your relational life path meets a universally oriented expression. You care about specific people deeply and about large-scale collective wellbeing. The risk is that the 9 expression uses the big picture as an escape from the specific demands of the 2 path, the hard individual relationship, the one conversation that matters more than the mission. Both dimensions are real. Don't let the large one perpetually displace the small one.",

    // Life Path 3
    "3-1": "Your expressive life path meets a direct, independent expression. You have both creative range and the conviction to push your work into the world without waiting for approval. The shadow: you may prioritize bold self-expression over quality. Getting the thing out quickly can mean not getting it fully developed. Learn to tolerate the slower, less glamorous stage of refinement, it's where the work actually becomes what it could be.",
    "3-2": "Your creative life path meets a relational, cooperative expression. At best, your creativity is in service of connection, your work brings people together or helps them understand each other. The risk: the 2 expression absorbs the creative energy into accommodation, you adapt your creative voice to what people seem to want rather than what you actually need to say. Don't mistake being liked for being effective.",
    "3-3": "Pure 3 energy, doubled. Enormous creative range, natural communicator, drawn toward expression in every available medium. The shadow is proportional: scattered to the point of paralysis, performing instead of creating, starting more than will ever be completed. The gift is real, but it requires a discipline that doesn't come naturally to you. Pick one form and go deep before you go broad.",
    "3-4": "Your expressive life path meets a structured, practical expression. This combination can produce work that is both original and durable. The friction: the 4 expression may feel like it's domesticating your creative impulse. It isn't. It's giving it the structural support that makes completion possible. Welcome the structure even when it chafes, the constraint is part of the craft.",
    "3-5": "Two freedom-oriented energies. High creativity, high adaptability, high resistance to constraint. The shadow is proportional: commitment is difficult, completion is rare, stimulation-seeking substitutes for the deeper satisfaction that comes through sustained work. You need genuine freedom, but you also need to find out what's on the other side of the difficult middle of a project. You won't find out if you always exit before you get there.",
    "3-6": "Your expressive life path meets a responsible, nurturing expression. You have both the creative voice and the care for others to create work that genuinely serves people. The shadow: the 6 expression can redirect all the creative energy toward maintaining and supporting others, leaving nothing for your own voice. Your art is not a luxury to be pursued when everything else is settled. It's a core function.",
    "3-7": "Your creative life path meets an analytic, interior expression. This can produce genuinely deep creative work, the art that has a real idea behind it, that doesn't mistake beauty for meaning. The risk: the 7 expression turns the 3's creative energy inward, producing the person who has enormous range but never shares it. What's perfect in your head is unavailable to everyone else. Let imperfection into the world.",
    "3-8": "Your creative life path meets a powerful, strategic expression. You have both the creative range and the executive capacity to build something significant. The risk: the 8 expression treats the 3's creativity as a resource to be optimized rather than a life to be lived. You may find yourself producing work that is impressive by external measures but hollow to you. Check whether you still love what you're making.",
    "3-9": "Your creative life path meets a universal, synthesizing expression. This combination can produce extraordinary communicators, people whose work addresses the human condition with both range and depth. The shadow: the ambition of the scope can make completion impossible. Something meant to address everything ends up finished by no one. Specific, concrete, particular, that's how the universal actually gets transmitted.",

    // Life Path 4
    "4-1": "Your structured life path meets a direct, autonomous expression. This combination can produce exceptional builders who operate with real independence and conviction. The shadow: a potentially suffocating commitment to being right. Your 4 path requires getting things right through careful work; your 1 expression insists on being the originator. When the right answer wasn't your idea, the dissonance is significant. Practice crediting others' contributions without feeling diminished by it.",
    "4-2": "Your disciplined life path meets a cooperative, relational expression. You are reliable in relationship in a way that many people are not, you show up, you follow through, you can be counted on. The shadow: you may treat relationships as maintenance tasks rather than as living things that require spontaneity and emotional risk. The structure is valuable; don't let it replace the warmth that should animate it.",
    "4-3": "Your structured life path meets a creative, expressive expression. This has genuine potential, the person who can both generate creative ideas and build systems to execute them. The friction: the 4 path asks for discipline that the 3 expression resists. You'll oscillate between productive structured periods and creative binges that feel like freedom but produce little. Maintain the creative practice even when it's not exciting.",
    "4-4": "Structure doubled. Extraordinary discipline, exceptional reliability, high capacity for sustained difficult work. The shadow is proportional: rigidity so complete that adaptation becomes impossible, rules adhered to long after they've stopped working, joylessness dressed up as virtue. Build in genuine play, not managed recreation, but actual unstructured time with permission to produce nothing. You need it more than you think.",
    "4-5": "Your structured life path meets a freedom-oriented, adaptable expression. This produces useful tension: the 4 path asks you to build things that last while the 5 expression needs them to change. At your best, you create structures that are robust without being rigid. At your worst, you oscillate between over-controlling and abandoning entirely. Learn to distinguish between the structure that serves and the structure that prevents.",
    "4-6": "Your disciplined life path meets a responsible, nurturing expression. Both energies take obligation seriously. The risk: you end up carrying enormous weight, the structure and the care, without adequate support. You will reliably show up for others. The question is who shows up for you. Be explicit about what you need rather than assuming others will notice and respond.",
    "4-7": "Your disciplined life path meets an analytic, interior expression. You think carefully and you work carefully. The combination can produce extraordinary expertise, the person who has genuinely mastered a specific domain through sustained, rigorous effort. The shadow: both energies can become defensive,4's rigidity meeting 7's intellectual superiority, producing someone who is rarely openly wrong because they're rarely genuinely open.",
    "4-8": "Two builder energies. Your life path creates the foundation and your expression pursues the scale. This combination can build significant things that actually work, not just impressive, but functional. The risk: the single-minded pursuit of the build crowds out everything else. Relationships, health, pleasure, all deferred until the project is done. The project is never done. Build some of those things in now, as operational requirement.",
    "4-9": "Your disciplined, structured life path meets a universally oriented expression. The 4 builds specific things; the 9 wants to serve everyone. The friction: the 9 expression may find the 4 path's specificity limiting, you want to address the large problem, and here you are managing a specific project. The integration: the specific, done well, is the only way the universal gets addressed at all. Scale starts with the thing in front of you.",

    // Life Path 5
    "5-1": "Freedom doubled in different registers. Your life path asks for change and your expression demands independence. Commitment of any kind, to people, projects, places, can feel like threat. You may have a long trail of incomplete things and hurt people who couldn't hold you. This isn't irredeemable, but it requires honest examination of what you're actually afraid of when things start to feel permanent. The freedom you're protecting, from what, exactly?",
    "5-2": "Your freedom-oriented life path meets a relational, cooperative expression. The tension is direct: the 5 wants to keep moving and the 2 wants sustained connection. You will be drawn into deep relationships and then feel confined by them. The people who love you experience this as abandonment even when you're physically present. The work: identify what specifically feels confining, vulnerability? obligation? predictability?, and address that directly rather than leaving.",
    "5-3": "Two freedom-energies with high creative potential. You're adaptable, expressive, interesting, and very difficult to pin down. The shadow: brilliant in the first act of anything, the exciting early phase, and consistently absent in the second act when depth is required. Your output is impressive; your follow-through is not. Develop one domain where you require yourself to stay past the interesting part.",
    "5-4": "Your freedom-seeking life path meets a structured, disciplined expression. The friction is valuable: the 5 needs constraint to produce anything meaningful, and the 4 expression provides structure. But the structure needs to serve the movement rather than prevent it. You are not a conventional builder, don't try to operate like one. Build mobile structures: systems that support change rather than resist it.",
    "5-5": "Pure 5 energy, doubled. Maximum freedom-seeking, maximum adaptability, maximum resistance to constraint. The shadow is severe: almost no capacity for the sustained commitment required by long projects, deep relationships, or real expertise. The gift is real, you are genuinely equipped for a world that changes faster than others can adapt. But you need to be deliberate about what you choose to stay with, or you'll look back on a life of extraordinary motion and limited meaning.",
    "5-6": "Your freedom-seeking life path meets a responsible, nurturing expression. The tension: the 5 wants to keep its options open while the 6 expression takes on obligations. You may spend significant energy trying to maintain freedom while simultaneously taking on commitments that close it. Choose your obligations deliberately and actually commit to the ones you choose, rather than maintaining the internal escape hatch.",
    "5-7": "Your change-oriented life path meets an analytic, interior expression. You think carefully about where you're going but you need to keep moving. The risk: the 7 expression uses analysis as a brake on the 5's necessary motion, you investigate options so thoroughly that you never choose among them. At some point, you need enough information to move, not perfect information. Learn to recognize when you've reached sufficient.",
    "5-8": "Your freedom-seeking life path meets a power-and-resource expression. This combination can build significant things quickly, you move fast and you command resources. The shadow: the 8 expression may try to hold what the 5 path needs to release. You'll build something, then need the evolution that the 8 resists surrendering. Don't confuse protecting what you've built with clinging to a structure that's run its course.",
    "5-9": "Your change-oriented life path meets a universal, synthesizing expression. Both energies operate at scale and resist narrow constraint. The risk: nothing ever becomes specific enough to be useful. You can see the large patterns and understand the need for change, but the specific implementable action keeps eluding you because you're always aware of the larger context. Sometimes the right move is the obvious next step, not the optimal global solution.",

    // Life Path 6
    "6-1": "Your responsibility-oriented life path meets a direct, autonomous expression. The tension: you feel responsible for others while also needing to operate independently. You may build dependencies around you and then resent them. Watch for the pattern where you solve everyone else's problems, establishing yourself as essential, and then feel trapped by the network you created. You chose it. Own that, and choose more deliberately going forward.",
    "6-2": "Relational sensitivity combined with heavy responsibility. You feel others' needs very precisely and feel obligated to address them. The accumulated weight over time is significant. The specific risk: you may confuse being needed with being loved, and structure your relationships to ensure need rather than genuine reciprocal care. Distinguish between care and management. The people in your life probably want the first.",
    "6-3": "Your responsible life path meets a creative, expressive expression. You have both the care for others and the creative range to produce things that genuinely serve people. The shadow: all the creative energy gets redirected into maintenance, managing the family, team, household, and your own voice goes silent. Your creativity is not supplementary to your service function; it is a core need.",
    "6-4": "Your nurturing life path meets a structured, disciplined expression. Both energies take their obligations seriously. The risk: you become the structural support for everyone around you while neglecting your own foundation. You maintain, you manage, you show up reliably, and at some point, something in you stops. Build the maintenance function for yourself with the same rigor you apply to everyone else.",
    "6-5": "Your responsibility-oriented life path meets a freedom-seeking expression. You feel obligated to stay and support while also feeling constrained by exactly that obligation. You may create elaborate commitments for yourself precisely because you don't trust yourself to stay otherwise. Examine whether your commitments are freely chosen or elaborate self-imposed constraints. The ones you'd walk away from if you could, those need renegotiation.",
    "6-6": "Pure 6 energy, doubled. Maximum sense of responsibility, maximum care, maximum risk of martyrdom. You can give everyone else exactly what they need and have nothing left for yourself. The path through this is not caring less, it's building non-negotiable self-care into your structure before the demand begins, not after. You require recovery time, pleasure, and experiences that serve no one else.",
    "6-7": "Your nurturing life path meets an analytic, interior expression. You care about people deeply and think carefully about what they need. At your best, this is wise, non-intrusive support, you don't project, you observe, you respond to what's actually there. The risk: the 7 expression can detach from the 6 path's emotional demands, producing someone who seems caring but is actually maintaining a carefully calibrated distance.",
    "6-8": "Your nurturing life path meets a powerful, resource-oriented expression. You have both the care for people and the capacity to build structures that serve them at scale. The risk: the 8 expression may try to manage what the 6 path genuinely loves. You can build an organization around care and gradually optimize the care out of it. Keep the original intention visible as the scale grows.",
    "6-9": "Your responsible life path meets a universal, collective expression. You feel personally responsible for specific people and collectively responsible for large-scale wellbeing. The weight of this is significant. The risk: using the universal concern as an escape from the specific demands of specific relationships. The person in front of you is also the world. Start there.",

    // Life Path 7
    "7-1": "Your interior, analytic life path meets a direct, autonomous expression. You think carefully and you lead clearly, when you decide to lead. The shadow: you can use the 7's need for analysis as a reason not to act when action is indicated. Your expression is direct, but only when the analysis feels complete. The analysis is rarely complete. Develop a tolerance for acting on sufficient information rather than waiting for perfect information.",
    "7-2": "Your interior life path meets a relational, cooperative expression. You live in your head but express yourself through connection. The friction: the 7 path values solitude and the 2 expression requires relationship. You need depth of relationship but also recovery time from it. You'll need to build relationships that explicitly accommodate this, that understand withdrawal is not rejection.",
    "7-3": "Your analytic life path meets a creative, expressive expression. At your best, you produce work with real intellectual depth expressed with creative range. The risk: the 3 expression may keep the output light and accessible while the 7 path demands precision. Or the 7's perfectionism prevents the 3's natural output from reaching completion. Let some imperfect work into the world. It will teach you more than continued refinement.",
    "7-4": "Your analytic life path meets a structured, practical expression. You think carefully and you build carefully. The combination can produce exceptional expertise in narrow domains. The risk: you can become so specialized and so methodical that adaptation becomes painful. Your precision is genuinely valuable. Ensure it's being applied to a domain that continues to develop rather than one you've outgrown.",
    "7-5": "Your interior life path meets a freedom-seeking expression. You think deeply but need to keep moving, settling in one place, relationship, or frame feels suffocating. The risk: you use the depth of your analysis as justification for the 5's resistance to commitment. 'I've examined this and it's not right' can mean 'I've examined this and I'm afraid.' Learn to distinguish the two.",
    "7-6": "Your analytic life path meets a nurturing, responsible expression. You think carefully about what people need and take genuine responsibility for providing it. The combination can produce exceptional depth of care, not sentimental, but precise. The risk: over-analysis of relational dynamics can cause you to withhold care while you're still evaluating whether it's appropriate. Sometimes what's needed is the response, not the assessment.",
    "7-7": "Pure 7 energy, doubled. Maximum interior depth, maximum analytical rigor, maximum resistance to exposure. The shadow: you may build an intellectually rich inner world and share almost none of it with anyone else. The work of your life may remain unpublished, unstated, unshared. That is a failure mode, not a virtue. Your conclusions require the test of other minds, not because they're wrong, but because they need the contact to be fully formed.",
    "7-8": "Your analytic life path meets a powerful, resource-oriented expression. You think in strategic depth and can command significant resources. The combination is potentially formidable. The risk: you may execute a plan with precision and scale without having examined whether it was the right plan. Check your premises. The intelligence that built the plan is capable of questioning it, but only if you make space for genuine doubt.",
    "7-9": "Your interior life path meets a universal, synthesizing expression. Both energies move toward the large picture, the underlying pattern, the structural truth. The risk: the abstraction never comes down to earth. The insight never becomes the specific, actionable, particular thing that changes someone's actual life. Develop tolerance for the concrete, it's how the abstract becomes useful.",

    // Life Path 8
    "8-1": "Power doubled. Your life is built around authority and your expression leads with independence. The combination is forceful, you pursue what you want directly and you have the capacity to build significant things. The shadow: your tolerance for opposition is very low and your patience for process is even lower. Some of the best paths forward require both. Develop the discipline to work with structures you didn't design.",
    "8-2": "Your power-oriented life path meets a cooperative, relational expression. Your 2 expression can modulate what would otherwise be raw force, and your 8 path gives your relational sensitivity real-world leverage. The shadow: the 2 expression can be used strategically, attuning to others' needs as a tool for influence rather than genuine response. Notice when you're using empathy as a management technique.",
    "8-3": "Your power-oriented life path meets a creative, expressive expression. You have both the ambition to build something significant and the creative range to find interesting ways to do it. The risk: the 8's drive for dominance treats the 3's creativity as a deliverable rather than a process. You may produce impressive things that feel hollow because the creative freedom was too constrained. The best output requires that you genuinely don't know the answer at the start.",
    "8-4": "Your powerful life path meets a structured, disciplined expression. Both energies are builders. The combination can produce lasting things of significant scale. The shadow: control. Both energies want to determine exactly how things go, which makes delegation painful and collaboration difficult. Your relationships are probably organized around authority, and the people who work with or for you may not feel seen as people. That matters.",
    "8-5": "Your power-oriented life path meets a freedom-seeking expression. The tension: the 8 wants to build and consolidate while the 5 expression needs to keep options open. You may build impressive structures and then dismantle them before they've reached their potential, or you may feel trapped in what you've created. Develop a clear distinction between the structures that need protecting and those that have run their course.",
    "8-6": "Your power-oriented life path meets a nurturing, responsible expression. You build at scale and you care about the people involved. This combination can produce leaders who genuinely develop their organizations rather than just extracting from them. The risk: paternalism. Your sense of what's good for others may be both accurate and insufficiently deferential to their own judgment. Give people more agency than feels comfortable.",
    "8-7": "Your power-oriented life path meets an analytic, interior expression. You think in strategic depth and pursue significant goals. The combination produces someone who is rarely outmaneuvered. The shadow: you may be so effective at managing situations to your advantage that you rarely encounter genuine opposition, and therefore rarely have your assumptions seriously challenged. Actively seek out people who will push back.",
    "8-8": "Pure 8 energy, doubled. Maximum ambition, maximum authority, maximum risk. The shadow at this level is significant: the pursuit of power can crowd out everything else, relationships, health, the question of what the power is actually for. High-functioning 8-8s often reach mid-life with impressive external achievements and a puzzling sense of vacancy. Don't wait for that moment to ask what it was all in service of.",
    "8-9": "Your power-oriented life path meets a universal, compassionate expression. You pursue significant goals and you genuinely care about collective wellbeing. The tension: the 8's drive for control and the 9's need for release. You may find it very difficult to let go of the outcomes your 9 expression theoretically endorses surrendering. Build things for a purpose larger than your own achievement, and then actually let them outgrow you.",

    // Life Path 9
    "9-1": "Your completion-oriented life path meets a direct, autonomous expression. You're here to conclude cycles and you express yourself with independence. The tension: the 9 path asks for release and the 1 expression wants to initiate. You may end things definitively and immediately start something new before the ending has been integrated. The lesson is staying with completion long enough for it to actually complete, rather than using new beginnings as escape.",
    "9-2": "Your universal-oriented life path meets a relational, cooperative expression. You care about the large picture and express that care through specific relationships. At your best, your individual relationships are themselves an expression of a larger ethic. The risk: the 9 path's tendency to avoid personal grief can make the 2 expression's relational depth feel threatening. The specific difficult relationship is the curriculum, not an obstacle to it.",
    "9-3": "Your completion-oriented life path meets a creative, expressive expression. You synthesize wide experience into creative work that speaks to something essential. At your best, you produce things that feel both personal and universal. The shadow: the 3 expression may keep things lighter than the 9 path's depth requires. Don't protect your audience from the difficult material, that's where the real usefulness lives.",
    "9-4": "Your universal-oriented life path meets a structured, disciplined expression. Both energies are serious about doing things right, for different reasons. The combination can produce someone who genuinely serves over the long term through consistent, disciplined work. The risk: the 4 expression can make the 9's natural surrender quality feel like failure. Sometimes the most disciplined thing is knowing when something is finished.",
    "9-5": "Your completion-oriented life path meets a freedom-seeking expression. Both energies resist permanence, the 9 through completion and the 5 through movement. The shadow: you move through relationships, places, and projects with genuine grace but without the sustained investment that creates real depth. Something can be well completed and still have been too short. Don't mistake elegant exit for wisdom.",
    "9-6": "Your universal-oriented life path meets a nurturing, responsible expression. Both energies care about collective wellbeing, and both have a martyrdom risk. The weight of what you feel responsible for, close relationships and the larger world, can be significant. Build in actual limits on what you take on. Not because care is wrong, but because unlimited care without recovery produces neither good relationships nor good service.",
    "9-7": "Your completion-oriented life path meets an analytic, interior expression. You see patterns clearly and think carefully about what they mean. At your best, you produce work of genuine depth that helps others make sense of their experience. The shadow: both energies avoid direct emotional engagement, the 9 through the universal frame, the 7 through analysis. Stay with the specific feeling long enough for it to be real.",
    "9-8": "Your universal-oriented life path meets a powerful, resource-oriented expression. You pursue significant goals and have the capacity to build things that matter. The specific tension: the 9 path ultimately requires surrender of what you've built, and the 8 expression resists that surrender intensely. Build for purposes that extend beyond your own achievement, things that succeed because they're bigger than you, not despite it.",
    "9-9": "Pure 9 energy, doubled. Maximum universal orientation, maximum compassion, maximum difficulty with personal specificity. The shadow: you can be so oriented toward the large and collective that specific people feel your actual presence only intermittently. The work is bringing the depth of your concern down to the particular, this person, this conversation, this moment, without losing the larger perspective that is genuinely yours.",
  },

  // ── Pinnacles ─────────────────────────────────────────────────────────────────

  pinnacles: {
    1: "A pinnacle of initiation and independence. During this period the curriculum is learning to act from your own conviction without external validation. You will face situations that require decision-making without consensus, and the capacity to lead will be tested in ways you may not feel ready for. Don't wait for permission. The cost is that mistakes are visible and yours alone; the gain is the development of genuine agency that no one can take from you.",
    2: "A pinnacle of relationship and collaboration. The primary lessons involve patience, sensitivity to others, and the willingness to be a supporting force rather than the lead. This is not a period of dramatic individual achievement, it's one where what you build is built with others, and the quality of those partnerships determines the outcome. Develop your capacity to listen and wait. This period rewards those who can.",
    3: "A pinnacle of creative expression and social development. Opportunities for self-expression, connection, and visibility arise naturally. The risk is using this period's social energy for surface momentum rather than genuine creative development. The lessons involve focusing what wants to scatter: your interests, your output, your attention. Where do you choose to go deep? That choice shapes the next phase significantly.",
    4: "A pinnacle of construction and discipline. Not an easy period. The curriculum is sustained effort over time, building foundations that may not produce obvious results for years. Patience with process is essential. You will face obstacles that are frustrating precisely because the solution is more effort, more structure, more discipline. This period rewards those who can tolerate the slow build without requiring visible progress as validation.",
    5: "A pinnacle of change and expansion. Movement, variety, and adaptability are the themes. Don't try to hold constant what this period is requiring you to release. The temptation is to maintain stability at the cost of the growth that change makes possible. The lesson is learning to direct change rather than simply being moved by it, keeping enough structural continuity to learn from the movement.",
    6: "A pinnacle of responsibility and service. Family, community, and care for others come to the foreground. You may take on significant responsibility for others, parenting, leading, supporting through difficulty. The curriculum tests whether your care is genuinely unconditional or whether it comes with unspoken requirements. And whether you can take on this much without losing yourself in the process.",
    7: "A pinnacle of inquiry and interior development. External momentum may slow while interior development accelerates. This period asks for depth over breadth, sustained focus on understanding something thoroughly. It's not a particularly sociable time. What you conclude during this period will shape your perspective for decades. Take the investigation seriously. Don't rush toward premature certainty because the uncertainty is uncomfortable.",
    8: "A pinnacle of ambition and material development. Power, resource, and the capacity to influence outcomes at scale are the themes. Significant material opportunity is possible, and significant material testing. The curriculum is whether you can handle authority without losing sight of why you wanted it. This period tends to put you in contact with the relationship between money, power, and integrity.",
    9: "A pinnacle of completion and transition. Major life chapters close during this period, phases that have served their purpose but need to end. The curriculum is release: of relationships, of identities, of ways of operating that worked before and no longer do. Grief is possible and appropriate. What ends makes space for what comes next, but only if the ending is allowed to be genuinely complete.",
    11: "A master pinnacle of heightened perception and potential influence. The sensitivity is amplified and so is the nervous system cost. You may experience periods of unusual clarity followed by complete exhaustion. The curriculum involves channeling the perception into sustained, grounded output, not dissipating it through anxious oversensitivity. Find the form your insight needs to take and build the technical skill to express it precisely.",
    22: "A master pinnacle of large-scale building and practical idealism. The scale of what's possible is genuinely unusual during this period, but so is the temptation to remain in the planning phase indefinitely. The curriculum is moving vision into specific, committed action. This requires tolerating imperfection in execution and refusing to be paralyzed by the gap between the ideal and the possible. Build something real.",
    33: "A master pinnacle of compassionate service and healing. The capacity to genuinely help others reaches its maximum during this period, as does the risk of self-erasure. The curriculum is discerning between service that is genuinely needed and service that is filling your own need to be needed. What do people in your life actually require from you right now? That answer, not your assumption of it, is the curriculum.",
  },

  // ── Challenges ────────────────────────────────────────────────────────────────

  challenges: {
    0: "The zero challenge is the rarest, indicating broad self-determination without a single dominant lesson. This sounds easier than it is. Without the focused pressure of a specific challenge, the work is choosing a direction without external necessity requiring it. The absence of a designated curriculum can produce genuine freedom or directionless drifting, the difference being the clarity of your own values and whether you've developed them deliberately rather than by default.",
    1: "The challenge of self-assertion. Recurring situations will test your ability to initiate, lead, and act without requiring external permission. You will encounter conditions that specifically undermine your autonomy, controlling relationships, structures that ignore your contributions. The work isn't to become combative; it's to develop internal authority that doesn't require external validation. Act from your own conviction, consistently, even when it produces no immediate result.",
    2: "The challenge of sensitivity and limits. You are wired to attune to others, and situations will repeatedly arise where that attunement costs you, where you agree to things you don't actually want, where avoiding conflict outweighs your own position. The work is developing a clear sense of where you end and others begin, and maintaining that limit even when it creates the discomfort you've been trained to prevent.",
    3: "The challenge of focus and depth. Your creative energy is real, but it scatters easily. The recurring pattern involves too many directions, projects started and abandoned, relationships maintained at surface distance. The work is choosing one domain and tolerating the discomfort of going deep, past the point of novelty, into the part where real skill is developed. Breadth without depth is eventually indistinguishable from noise.",
    4: "The challenge of structure and discipline. The recurring theme involves situations requiring sustained effort, methodical progress, and patience with slow development. You will be asked repeatedly to do the work without the reward, to maintain structure when everything in you wants to abandon it. The work is not learning to love discipline, it's learning to tolerate it long enough for it to produce something real.",
    5: "The challenge of freedom and responsibility. The recurring pattern is the tension between your need for change and movement and the demands of commitment. The work is not becoming less free, it's developing the capacity to choose your commitments deliberately and honor them. Real freedom is the ability to commit, not the absence of it. You will be tested on this distinction repeatedly.",
    6: "The challenge of responsibility and self-care. The recurring pattern involves being asked to take on more than your fair share of care and obligation. You will be drawn into situations requiring you to manage, support, and maintain. The work is discerning which responsibilities are genuinely yours and which you've absorbed because no one else stepped up. Setting limits is not abandonment, it's clarity about what you can actually sustain.",
    7: "The challenge of trust and openness. The recurring pattern involves situations that test your capacity to let people in, to be known rather than knowing, to be vulnerable rather than analyzing. You will repeatedly face the choice between genuine engagement and intellectual withdrawal. The work is developing willingness to be wrong in front of people, to not have the answer, to stay in a situation past the point of comfort.",
    8: "The challenge of power and integrity. The recurring pattern involves significant tests of how you handle authority, resource, and influence. Money and power will feature prominently, and the situations that arise will specifically test whether you can hold both without letting them corrupt your judgment. The work is maintaining the question of what the power is for, especially when it becomes sufficient to avoid the question.",
    9: "The challenge of completion and release. The recurring pattern involves situations requiring you to let go, of relationships, phases, identities, beliefs that are finished. You will repeatedly be confronted with things that need ending, and your resistance to those endings will be the primary obstacle. The work is developing tolerance for loss, not as stoicism, but as recognition that completion is not failure.",
  },

  // ── Life Cycles ───────────────────────────────────────────────────────────────

  lifeCycles: {
    1: "A life cycle of self-development and independence. The dominant energy is individual: who you are separate from the roles and relationships around you. The work is establishing your own direction, your own values, your own way of operating, not in reaction to others, but as genuine expression of self. Opportunities for initiative and autonomy appear. Take them seriously. This is the cycle where the foundation of identity gets laid.",
    2: "A life cycle of relationship and development through partnership. The central curriculum is what you learn from and through the people close to you. Collaboration, cooperation, and the question of how to be a genuine partner without losing yourself in the process are the themes. The quality of your relationships during this cycle shapes the rest of your development in ways that solo achievement cannot.",
    3: "A life cycle of creative expression and social development. This period amplifies the drive to express, through art, communication, relationship, building. The energy here is outward and generative. The risk is dispersal: this cycle can spread attention across too many directions. The work is channeling the expressive energy into something that can actually be developed over time.",
    4: "A life cycle of building and discipline. The foundational work of this period is real, the structures you build will either support or constrain you for decades. This isn't always glamorous work, and it usually isn't fast. The curriculum is patience: the ability to continue methodical work when the results are delayed. What you build here should actually stand. Build accordingly.",
    5: "A life cycle of change, travel, and expansion. Movement, geographic, professional, relational, intellectual, is characteristic of this period. The risk is treating all movement as equivalent and missing the specific changes that have genuine developmental content. The curriculum is learning to direct change: to initiate the shifts that need to happen rather than simply being moved by events.",
    6: "A life cycle of responsibility and service. Home, family, and community are central themes. This is often a period of taking on significant obligations, for others' wellbeing, for the maintenance of relationships and structures. The curriculum involves both genuine service and the limits of service: what you can sustainably provide and what others need to develop themselves.",
    7: "A life cycle of introspection and specialization. External momentum slows; interior development accelerates. This is a period of deepening, of studying, refining, developing genuine mastery in a specific domain. Social life may contract. That's appropriate. What you understand by the end of this cycle should have real depth that broad engagement couldn't have produced.",
    8: "A life cycle of material development and authority. Ambition, resource, and the capacity to influence significant outcomes are the themes. Opportunities for material achievement appear, and the tests of how you handle them are equally significant. The curriculum is building something substantial while maintaining the perspective on why it matters.",
    9: "A life cycle of completion and transition. This period brings major chapters to close. The work is authentic ending, allowing what is finished to be finished, grieving what has been lost, releasing what no longer serves. The quality of this completion determines what becomes available in the next cycle. Don't shortcut the ending by starting the next thing prematurely.",
  },

  // ── Personal Years ────────────────────────────────────────────────────────────

  personalYears: {
    1: "This is an initiation year. What you begin now, a project, a relationship, a direction, will shape the next nine-year cycle significantly. Act from genuine conviction rather than habit or momentum. Don't start things you're not actually interested in completing, because this year's choices carry longer-term implications than usual. The energy favors bold, specific action over careful planning. The question to answer before the year is out: what do you actually want to build, and are you willing to commit to it?",
    2: "This is a year of partnership and patience. The momentum of year 1 doesn't continue, and trying to force it will exhaust you. Year 2 rewards cultivation over initiation: deepening what already exists, attending to relationships and processes that need quiet development. Collaboration is central. Pay attention to who you're working with and whether those partnerships are genuinely reciprocal. The temptation to force progress faster than this year supports is the primary pitfall.",
    3: "This is a year of expression and social expansion. Creative output, connection, and visibility increase naturally. The energy is outward and generative, this is not a year for retreat. The pitfall is dispersal: the 3 year can spread attention across too many directions, producing a lot of activity without depth or completion. Choose where you're actually investing, rather than saying yes to everything because the energy is high.",
    4: "This is a year of foundation and discipline. Not exciting, often demanding. The work of year 4 is building structures that will support what comes later, in work, relationships, and health. Shortcuts taken in year 4 tend to produce problems in years 6 and 7. The energy doesn't reward new initiatives; it rewards systematic development of what already exists. What needs to be properly built rather than hastily assembled?",
    5: "This is a year of change and freedom. What was stable becomes fluid; what felt fixed will move. This isn't a crisis, it's the curriculum. Year 5 brings necessary disruption. The pitfall is reacting to every change without choosing which ones to direct. Your job is to identify the changes that need to happen and facilitate them, rather than being entirely reactive to events you didn't initiate.",
    6: "This is a year of responsibility and relationship. Family, partnership, and community obligations come to the foreground. This is a year where others need you, or will ask more than is sustainable. The question isn't whether to engage responsibly; it's whether the responsibility you take on is actually yours. Year 6 has a strong pull toward taking on too much. Be deliberate about what you can genuinely commit to without compromising your own foundations.",
    7: "This is a year of introspection and reassessment. The external pace slows, or should. Year 7 rewards going inward: studying, refining, evaluating what has been built so far in this nine-year cycle. Avoid forcing major new initiatives. The energy is better spent deepening understanding of what already exists. Solitude has value this year that it doesn't in others. Use it for genuine reflection rather than avoidance.",
    8: "This is a year of power and material development. What was cultivated through years 1-7 can now produce results at scale. Ambition is appropriate; so is clear-eyed strategy. Year 8 rewards bold, informed action in the material world. The pitfall is confusing busyness with power or accumulation with achievement. What specifically are you building this year, and why? The answer should be specific enough that someone could verify whether you succeeded.",
    9: "This is a completion year. The nine-year cycle closes. What needs to end must end, in relationships, commitments, identities, ways of operating that served their purpose and are finished. This is not a year to start significant new things; it's a year to close things well. Grief is possible and appropriate, completion includes loss. What you release in year 9 makes genuine space for what year 1 will initiate. The quality of the release determines the quality of the next beginning.",
  },

}

// ─── Backward-compat export (used by existing components) ─────────────────────

const ARCHETYPE: Record<number, string> = {
  1: 'The Pioneer',
  2: 'The Diplomat',
  3: 'The Communicator',
  4: 'The Builder',
  5: 'The Explorer',
  6: 'The Nurturer',
  7: 'The Analyst',
  8: 'The Strategist',
  9: 'The Humanitarian',
  11: 'The Illuminator',
  22: 'The Master Builder',
  33: 'The Healer',
}

export const INTERPRETATIONS: Record<number, NumberInterpretation> = Object.fromEntries(
  Object.entries(interpretations.numbers).map(([k, v]) => {
    const n = Number(k)
    return [n, {
      archetype: ARCHETYPE[n] || `Number ${n}`,
      meaning: v.general,
      positive: v.strengths,
      shadow: v.weaknesses,
      advice: v.advice,
      career: v.expression,
      love: v.soulUrge,
      money: v.lifePath,
    }]
  })
)
